### ISSUE TITLE
Group names of subscriber's abos surrounded by spans?

### ISSUE THREAD

**Issue by mindeffects** [gadgetto/GoodNews#65] opened 2019-02-26 08:46 UTC
Editing a subscriber's abos in GN 1.5.1-pl2 looks strange. The group names are surrounded by spans:

![image](https://user-images.githubusercontent.com/458619/53398625-56808e80-39aa-11e9-9903-5c8e6c4d4b8f.png)

Just wondering, if this is a MODX 2.7.1 thing because I never saw that behaviour while using MODX 2.7.0.

**Comment by gadgetto** [comment] 2019-02-26 08:55
Hi Oliver,

Thanks for reporting this!

I can reproduce the Problem - and it seem to be indeed based on the latest 2.7.1 update. I’ll have a look at this and try to fin a fix.

Greetings,
Martin

**Comment by gadgetto** [comment] 2019-02-26 16:43
This is very strange! I can reproduce it in one installation but not in an other one. All tested under 2.7.1.
What could cause this?

Chrome Web-Inspector in working installation:




Same Web-Inspector in non working install:
(the grey <span> part looks like the browser can’t recognize this as HTML and renders a string only)



Never seen such a behavior before.

Any idea?

**Comment by gadgetto** [comment] 2019-02-26 16:48
This is very strange! I can reproduce it in one installation but not in an other one. All tested under 2.7.1.
What could cause this?

Chrome Web-Inspector in working installation:

![working-version](https://user-images.githubusercontent.com/876737/53430333-979a9200-39ee-11e9-8353-22e40a9cb00d.png)

Same Web-Inspector in non working install:
(the grey <span> part looks like the browser can’t recognize this as HTML and renders a string only)

![non-working-version](https://user-images.githubusercontent.com/876737/53430351-9e290980-39ee-11e9-9b0c-f39a684625b7.png)

Never seen such a behavior before.

Any idea?

**Comment by gadgetto** [comment] 2019-02-26 17:29
I implemented a fix. Will be released in next update!

**Closed** 2019-02-26 17:31 UTC
Labels: bug, public
