### ISSUE TITLE
Sending errors with Goodnews

### ISSUE THREAD

**Issue by zahlenhexe** [gadgetto/GoodNews#82] opened 2020-07-08 18:51 UTC
I wrote already in the [Forum](https://community.modx.com/t/sending-errors-with-goodnews/2439), that GoodNews is not sending the mailings without errors. 
Today's mailing failed again with 86 out of 266 recipients. 

I turned on the systemsetting for goodnews.debug but there is nothing in the logfile. The setting_goodnews.worker_process_limit is 4, I think thats default. I'm sending through SMTP wich works for many of the mails but not for all. 

During the sendingprocess it seems to produce these errors during the restart of cron. 
These errors always appears for nearly one minute. Then Goodnews is sending mails for 5 seconds to get stuck again for 55s. 

I'm starting cron every minute through php but without sid. 
I can't find any errors in the server log either.

**Comment by navtsi** [comment] 2021-08-10 07:07
I have a familiar problem. CronJob will be proceed without any errors. But nothing will be sent. I activated Debug mode but there are no entries. After a while I got a sending error in the report, but no more informations. Reports are sent normally.
I have a second, old and unused installation with MODx 2.7.1. There everything works. 

Perhaps the problem is 2.8.x? I found some errors in Apache Log:

`AH01068: Got bogus version 100, referer: https://openwestend.de/owedit/?a=index&namespace=goodnews
2021-08-09 20:49:28 | Error | 92.117.146.18 | (22)Invalid argument: AH01075: Error dispatching request to :, referer: https://openwestend.de/owedit/?a=index&namespace=goodnews`

It's really sad, because Goodnews is best extra for newsletters. I don't want to switch.

**Comment by zahlenhexe** [comment] 2021-08-10 07:29
I think this is not the same sending error. This issue was solved due to provider settings/goodnews settings.
You can take the settings from [forum](https://community.modx.com/t/sending-errors-with-goodnews/2439/8?u=toelva) to exclude that. 
Perhaps your problem is actually related to 2.8.x.

**Comment by navtsi** [comment] 2021-08-10 07:51
Deactivating the multiprocessing was the solution. Strange because I have the server under my control and it worked in the past. But I sent the last mailing one year ago.
Thanks

**Comment by gadgetto** [comment] 2021-08-10 08:28
Is php exec still enabled on your server?

**Comment by gadgetto** [comment] 2021-08-10 08:29
I have no problems here running GoodNews on a 2.8.x installation.

**Comment by gadgetto** [comment] 2021-10-16 16:49
Closing this issue

**Closed by gadgetto** 2021-10-16 16:49 UTC
