### ISSUE TITLE
modAction support is deprecated since version 2.3.0.

### ISSUE THREAD

**Issue by karamble** [gadgetto/GoodNews#66] opened 2019-03-09 21:53 UTC
I get this warning during install:

![screen_024](https://user-images.githubusercontent.com/25404928/54077769-80e11e80-42bd-11e9-9d9f-65f6423f98e8.jpg)

**Comment by gadgetto** [comment] 2019-03-11 09:42
Yep, this is not a bug and will be changed in one of the next versions.

**Comment by gadgetto** [comment] 2020-05-18 16:38
Fixed in latest release

**Closed by gadgetto** 2020-05-18 16:38 UTC
